### PR TITLE
feat: custom temperature unit parameter

### PR DESCRIPTION
**Pull request by geenva**

### CODE REVIEW

**Comment by geenva** [comment]
Can't test this locally as I do not have an OpenWeatherMap API key. Can you authorise the Vercel deployment request please?

**Comment by geenva** [comment]
Should work now, tested on my end.

**Comment by geenva** [comment]
> If you could change it so if the value for unit is not F or C, it just defaults to F, that would be great; it'd prevent against stuff like this haha image

Of course... never thought of this. Will fix this.

**Comment by cnrad** [comment]
Awesome, thanks so much

**Pull request merged**
